[package]
name = "grid-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "2.0.1"
gaussian_blur = "0.1.1"
grid = "0.13.0"
macroquad = "0.4.4"
